// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC_AbVPkhf-nnGlo0EQ-gR2-drm5Mp8JJI',
    appId: '1:339922420964:web:2573dce3129663538e18f1',
    messagingSenderId: '339922420964',
    projectId: 'workshop-2-26086',
    authDomain: 'workshop-2-26086.firebaseapp.com',
    databaseURL: 'https://workshop-2-26086-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'workshop-2-26086.appspot.com',
    measurementId: 'G-K1395VG0Q8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDUqyOYlX75HTRI7L6tKeOCpLWblh24MI8',
    appId: '1:339922420964:android:6a08f7d250bc9a368e18f1',
    messagingSenderId: '339922420964',
    projectId: 'workshop-2-26086',
    databaseURL: 'https://workshop-2-26086-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'workshop-2-26086.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC1sKgaFhixzCdnLTlT-CX2EDQqBOg0vFo',
    appId: '1:339922420964:ios:ea16d9bf342c9bc98e18f1',
    messagingSenderId: '339922420964',
    projectId: 'workshop-2-26086',
    databaseURL: 'https://workshop-2-26086-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'workshop-2-26086.appspot.com',
    iosBundleId: 'com.example.wastewisee',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC1sKgaFhixzCdnLTlT-CX2EDQqBOg0vFo',
    appId: '1:339922420964:ios:c94b15508c531aa48e18f1',
    messagingSenderId: '339922420964',
    projectId: 'workshop-2-26086',
    databaseURL: 'https://workshop-2-26086-default-rtdb.asia-southeast1.firebasedatabase.app',
    storageBucket: 'workshop-2-26086.appspot.com',
    iosBundleId: 'com.example.wastewisee.RunnerTests',
  );
}
